# Generated by Django 2.2.3 on 2019-08-16 20:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=30, null=True)),
                ('review_content', models.CharField(max_length=200, null=True)),
                ('review_published', models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 13, 30, 247773), verbose_name='data published')),
                ('professor_name', models.CharField(max_length=20)),
                ('gradeReceived', models.CharField(max_length=2)),
                ('easyRating', models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('InterestingRating', models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('homework', models.BooleanField()),
                ('pop_quizzes', models.BooleanField(null=True)),
                ('numProjects', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('numTests', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('testDiff', models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('time_spent', models.IntegerField(blank=True, help_text='For classes that took more than 15 hours, just put 15', null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 13, 30, 246286), verbose_name='data published')),
            ],
        ),
    ]
