# Generated by Django 2.2.3 on 2019-07-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 17, 3, 6, 648440), verbose_name='data published'),
        ),
    ]
