# Generated by Django 2.2.3 on 2019-08-08 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190730_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 19, 17, 29, 435377), verbose_name='data published'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.ManyToManyField(to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courseNum', models.CharField(max_length=10)),
                ('gradeReceived', models.CharField(max_length=2)),
                ('easyRating', models.IntegerField()),
                ('InterestingRating', models.IntegerField()),
                ('time_spent', models.IntegerField()),
                ('homework', models.BooleanField()),
                ('numProjects', models.IntegerField()),
                ('numTests', models.IntegerField()),
                ('testDiff', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Department')),
            ],
        ),
    ]
