# Generated by Django 2.2.3 on 2019-08-08 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190808_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseNum',
            new_name='courseNumber',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 19, 23, 59, 810013), verbose_name='data published'),
        ),
    ]
