# Generated by Django 2.2.3 on 2019-08-12 18:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190808_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='InterestingRating',
            field=models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='easyRating',
            field=models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='testDiff',
            field=models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_spent',
            field=models.IntegerField(blank=True, help_text='For classes that took more than 15 hours, just put 15', null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 18, 49, 58, 619324), verbose_name='data published'),
        ),
    ]
