# Generated by Django 2.2.3 on 2019-08-16 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190816_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseNumber',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 27, 24, 352581), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 27, 24, 351103), verbose_name='data published'),
        ),
    ]
