# Generated by Django 2.2.3 on 2019-08-16 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190816_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review_content',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 29, 59, 999963), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 13, 29, 59, 999067), verbose_name='data published'),
        ),
    ]
