# Generated by Django 2.2.3 on 2019-08-16 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190816_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='webcast',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 14, 13, 6, 393184), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 14, 13, 6, 392215), verbose_name='data published'),
        ),
    ]
