# Generated by Django 2.2.3 on 2019-08-21 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190819_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradeReceived',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 3, 9, 405254), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 3, 9, 404129), verbose_name='data published'),
        ),
    ]
