# Generated by Django 2.2.3 on 2019-08-21 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190821_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 8, 22, 434821), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 8, 22, 433100), verbose_name='data published'),
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.School')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseNum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.SchoolCourse'),
        ),
    ]
