# Generated by Django 2.2.3 on 2019-08-21 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190821_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseNum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 24, 4, 465691), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 24, 4, 464589), verbose_name='data published'),
        ),
        migrations.DeleteModel(
            name='SchoolCourse',
        ),
    ]
