# Generated by Django 2.2.3 on 2019-08-21 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190821_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 24, 35, 259131), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 24, 35, 257459), verbose_name='data published'),
        ),
    ]
