# Generated by Django 2.2.3 on 2019-08-21 17:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190821_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('review_title', models.CharField(blank=True, max_length=30, null=True)),
                ('review_content', models.TextField(blank=True, max_length=200, null=True)),
                ('review_published', models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 40, 27, 918102), verbose_name='data published')),
                ('professor_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('gradeReceived', models.CharField(blank=True, max_length=2)),
                ('easyRating', models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('InterestingRating', models.IntegerField(blank=True, help_text='(1)= :D (5)= >:(', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 40, 27, 916539), verbose_name='data published'),
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.School')),
            ],
        ),
    ]
