# Generated by Django 2.2.3 on 2019-08-22 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190822_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbrev',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='InterestingRating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='easyRating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradeReceived',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('NP', 'NP'), ('P', 'P'), ('N/A', 'N/A')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='homework',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='numProjects',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='numTests',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pop_quizzes',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 16, 8, 35, 662339), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Review Title: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='testDiff',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_spent',
            field=models.CharField(blank=True, choices=[('1', '0-2'), ('2', '3-4'), ('3', '5-6'), ('4', '7-8'), ('5', '9-10'), ('6', '10-12'), ('7', '12-14'), ('8', '15-17'), ('9', '18-20'), ('10', '20+')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='webcast',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 16, 8, 35, 659639), verbose_name='data published'),
        ),
    ]
