# Generated by Django 2.2.3 on 2019-08-23 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190822_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseNum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.SchoolCourse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 9, 30, 2, 190094), verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 9, 30, 2, 187994), verbose_name='data published'),
        ),
    ]
