# Generated by Django 2.2.3 on 2019-08-23 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190823_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseNum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.SchoolCourse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 9, 34, 3, 895216), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 9, 34, 3, 892258), verbose_name='data published'),
        ),
    ]
